version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "@opentelemetry/*" # ignore otel dependencies until patches aren't needed
    schedule:
      interval: "weekly"
