version: 2
updates:
  - package-ecosystem: "pnpm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    labels:
      - automerge