services:
  quickwit:
    image: quickwit/quickwit
    volumes:
      - ./qwdata:/quickwit/qwdata
    environment:
      QW_ENABLE_OPENTELEMETRY_OTLP_EXPORTER: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://127.0.0.1:7281"
    ports:
      - 7280:7280
    command: [ "run" ]
    attach: false # comment this line if you'd like to view quickwit log output

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./config/otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4318:4318" # otlp http
      - "4317:4317" # otlp grpc
    restart: always
    depends_on:
      - quickwit
      - prometheus
  grafana:
    image: grafana/grafana-oss
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./config/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./config/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/quickwit-oss/quickwit-datasource/releases/download/v0.4.1/quickwit-quickwit-datasource-0.4.1.zip;quickwit-quickwit-datasource
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=metricsSummary
    ports:
      - "3000:3000" # ui
      # - "${MAP_HOST_GRAFANA:-127.0.0.1}:3000:3000"
    attach: false

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090"
