{
 "title": "OpenTelemetry Browser Extension",
 "description": "A demo dashboard for visualizing data generated by the OpenTelemetry Browser Extension.",
 "time": { "from": "2024-03-24T23:59:02.265Z", "to": "2024-03-25T00:13:16.810Z" },
 "templating": {
  "list": [
   { "name": "logFilter", "label": "Filter logs" },
   { "name": "traceFilter", "label": "Filter traces" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 17, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"font-family:monospace;\">\n    <h1 style=\"font-family:monospace;\">👋 Welcome! / 📚 README</h1>\n    <p>\n        Thanks for taking the time to check out the project. If you feel the urge, please consider contributing to the\n        project or <a href=\"https://github.com/sponsors/tbrockman\">sponsoring the developer</a>.\n    </p>\n    <p>\n        <b>\n            <h3 style=\"font-family:monospace;\">Don't see any data here?</h3>\n        </b> Check out <a href=\"https://github.com/tbrockman/opentelemetry-browser-extension\">the\n            FAQ.</a>\n    </p>\n    <h3 style=\"font-family:monospace;\">Demo</h3>\n    <p> This dashboard is meant to serve as a basic demonstration of the kind of queries and visualizations you can make\n        with some of the data you collect with the extension.</p>\n    <p>\n        It's currently under development, so there might be a bug or missing feature or two.\n    </p>\n    <h3 style=\"font-family:monospace;\">How to query the data</h3>\n    <p>The data in this dashboard primarly leverages <a href=\"https://quickwit.io\">Quickwit</a> (currently stores\n        traces in Tempo as well, but this may change in the near future). Quickwit supports a Lucene-like query\n        language (and Elasticsearch-search compatible API) which\n        you can learn\n        more about <a href=\"https://quickwit.io/docs/reference/query-language\">here</a>.</p>\n\n    <p>At the top of the dashboard you can also filter by log and trace attributes, which will automatically apply to\n        the\n        related dashboard visualizations.</p>\n</div>"
   },
   "targets": [
    {
     "bucketAggs": [
      { "field": "", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ]
    }
   ]
  },
  {
   "title": "Document load + document fetch times",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "span_attributes.http.url",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      },
      {
       "field": "span_name",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "span_duration_millis", "id": "1", "settings": { "missing": "0" }, "type": "sum" }
     ],
     "query": "(span_name:\"documentFetch\" OR span_name:\"documentLoad\")"
    }
   ]
  },
  {
   "title": "Webpage activity",
   "type": "timeseries",
   "description": "Count of clicks/scrolls/keypresses/submits per minute per website",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "span_attributes.http.url",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "span_attributes.event_type",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "span_start_timestamp_nanos", "id": "2", "settings": { "interval": "1m" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "span_attributes.event_type:\"click\" OR span_attributes.event_type:\"keypress\" OR span_attributes.event_type:\"scroll\" OR span_attributes.event_type:\"submit\""
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "Console logs captured and re-emitted by the extension",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 10 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "1000", "sortDirection": "desc" }, "type": "logs" }
     ]
    }
   ]
  },
  {
   "title": "Average request time (by URL and HTTP method)",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 8, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "span_attributes.http.url",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "50" },
       "type": "terms"
      },
      {
       "field": "span_attributes.http.method",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "span_duration_millis", "id": "3", "type": "avg" }
     ],
     "query": "*"
    }
   ]
  },
  {
   "title": "Total request time (by URL and HTTP method)",
   "type": "piechart",
   "gridPos": { "h": 17, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "span_attributes.http.url",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "3", "size": "50" },
       "type": "terms"
      },
      {
       "field": "span_attributes.http.method",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "50" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "span_duration_millis", "id": "3", "type": "sum" }
     ],
     "query": "*"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 34 },
   "targets": [
    { "limit": 20, "query": "{}", "tableType": "traces" }
   ]
  }
 ]
}