apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  uid: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus:9090
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  jsonData:
    httpMethod: GET
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: false
  apiVersion: 1
  uid: tempo
  jsonData:
    httpMethod: GET
    serviceMap:
      datasourceUid: prometheus
- name: Quickwit Logs
  uid: quickwit-logs
  type: quickwit-quickwit-datasource
  url: http://quickwit:7280/api/v1
  editable: false
  jsonData:
    index: 'otel-logs-v0_7'
    logMessageField: body.message
    logLevelField: severity_text
- name: Quickwit Traces
  uid: quickwit-traces
  type: quickwit-quickwit-datasource
  url: http://quickwit:7280/api/v1
  editable: false
  isDefault: true
  jsonData:
    index: 'otel-traces-v0_7'
