receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"
      grpc:
        endpoint: 0.0.0.0:4317
exporters:
  otlp/quickwit:
    endpoint: http://quickwit:7281
    tls:
      insecure: true
  debug:
    verbosity: detailed
service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/quickwit, debug]
    logs:
      receivers: [otlp]
      exporters: [otlp/quickwit, debug]