receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"
exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlp/quickwit:
    endpoint: quickwit:7281
    tls:
      insecure: true
  debug:
    verbosity: detailed
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp, otlp/quickwit]
    logs:
      receivers: [otlp]
      exporters: [otlp/quickwit, debug]